export const RATING = {
  EXCELLENT: 'excellent',
  GOOD: 'good',
  OKAY: 'okay',
  AVOID: 'avoid',
}
export const ROLE_TEXT = {
  admin: 'ادمین',
  adviser: 'مشاور',
}
export const USER_BADGE = {
  NEW: 'new',
  SILVER: 'silver',
  PLATINUM: 'platinum',
  GOLD: 'gold',
} as const

export const propertyDetailsMapping = {
  adviserName: 'نام مشاور',
  // PropertyOwnerFirstName: 'نام مالک',
  // PropertyOwnerLastName: 'نام خانوادگی مالک',
  // PropertyOwnerPhone: 'شماره تلفن مالک',
  dealType: 'نوع معامله',
  usage: 'نوع استفاده',
  propertyType: 'نوع ملک',
  warehouse: 'انباری',
  parking: 'پارکینگ',
  separatedoor: 'در جداگانه',
  terrace: 'بالکن',
  toilet: 'سرویس بهداشتی',
  burglaralarm: 'دزدگیر',
  centralantenna: 'آنتن مرکزی',
  pool: 'استخر',
  elevator: 'آسانسور',
  Janitor: 'سرایدار',
  Heater: 'دستگاه گرمایشی',
  cooler: 'دستگاه سرمایشی',
  isChange: 'قابلیت تبدیل',
  floor: 'نوع کف',
  Cabinet: 'نوع کابینت',
  // price: 'قیمت',
  area: 'متراژ',
  lifespan: 'قدمت',
  floorcount: 'تعداد طبقات',
  unit: 'تعداد واحد',
  countOfFloor: 'تعداد واحد در هر طبقه',
  countOfUnit: 'تعداد کل واحدها',
  // id: 'شماره فایل',
  // region: 'منطقه',
  // street: 'خیابان',
  // alley: 'کوچه',
  // zip_code: 'کد پستی',
  // lat: '',
  // lng: '',
  // galleryImage: '',
  // galleryVideo: '',
}
